var names = [];

var addUnique = function() {
	for(var i=0; i < arguments.length; i++) {
		var name = arguments[i];
		if(names.indexOf(name) >= 0) 
			continue;
		names.push(name);
	}
}

addUnique(
	//Resource types
	'AvailabilityZones', 'Cooldown', 'DesiredCapacity', 'HealthCheckGracePeriod', 'HealthCheckType', 'InstanceId', 'LaunchConfigurationName', 'LoadBalancerNames', 'MaxSize', 'MetricsCollection', 'MinSize', 'NotificationConfigurations', 'PlacementGroup', 'Tags', 'TerminationPolicies', 'VPCZoneIdentifier',
	'AssociatePublicIpAddress', 'BlockDeviceMappings', 'ClassicLinkVPCId', 'ClassicLinkVPCSecurityGroups', 'EbsOptimized', 'IamInstanceProfile', 'ImageId', 'InstanceId', 'InstanceMonitoring', 'InstanceType', 'KernelId', 'KeyName', 'PlacementTenancy', 'RamDiskId', 'SecurityGroups', 'SpotPrice', 'UserData',
	'AutoScalingGroupName', 'DefaultResult', 'HeartbeatTimeout', 'LifecycleTransition', 'NotificationMetadata', 'NotificationTargetARN', 'RoleARN',
	'AdjustmentType', 'AutoScalingGroupName', 'Cooldown', 'MinAdjustmentStep', 'ScalingAdjustment',
	'AutoScalingGroupName', 'DesiredCapacity', 'EndTime', 'MaxSize', 'MinSize', 'Recurrence', 'StartTime', 
	'accessKeyId', 'buckets', 'password', 'secretKey', 'type', 'uris', 'username', 'roleName',
	'ServiceToken',
	'NotificationARNs', 'Parameters', 'TemplateURL', 'TimeoutInMinutes',
	'Count', 'Handle', 'Timeout',
	'DistributionConfig',
	'IncludeGlobalServiceEvents', 'IsLogging', 'S3BucketName', 'S3KeyPrefix', 'SnsTopicName',
	'ActionsEnabled', 'AlarmActions', 'AlarmDescription', 'AlarmName', 'ComparisonOperator', 'Dimensions', 'EvaluationPeriods', 'InsufficientDataActions', 'MetricName', 'Namespace', 'OKActions', 'Period', 'Statistic', 'Threshold', 'Unit',
	'Activate', 'Description', 'Name', 'ParameterObjects', 'ParameterValues', 'PipelineObjects', 'PipelineTags',
	'AttributeDefinitions', 'GlobalSecondaryIndexes', 'KeySchema', 'LocalSecondaryIndexes', 'ProvisionedThroughput', 'TableName',
	'BgpAsn', 'IpAddress', 'Tags', 'Type',
	'DomainName', 'DomainNameServers', 'NetbiosNameServers', 'NetbiosNodeType', 'NtpServers', 'Tags',
	'InstanceId', 'Domain',
	'AllocationId', 'EIP', 'InstanceId', 'NetworkInterfaceId', 'PrivateIpAddress',
	'AvailabilityZone', 'BlockDeviceMappings', 'DisableApiTermination', 'EbsOptimized', 'IamInstanceProfile', 'ImageId', 'InstanceInitiatedShutdownBehavior', 'InstanceType', 'KernelId', 'KeyName', 'Monitoring', 'NetworkInterfaces', 'PlacementGroupName', 'PrivateIpAddress', 'RamdiskId', 'SecurityGroupIds', 'SecurityGroups', 'SourceDestCheck', 'SubnetId', 'Tags', 'Tenancy', 'UserData', 'Volumes',
	'Tags',
	'Tags', 'VpcId',
	'CidrBlock', 'Egress', 'Icmp', 'NetworkAclId', 'PortRange', 'Protocol', 'RuleAction', 'RuleNumber',
	'Description', 'GroupSet', 'PrivateIpAddress', 'PrivateIpAddresses', 'SecondaryPrivateIpAddressCount', 'SourceDestCheck', 'SubnetId', 'Tags',
	'DeleteOnTermination', 'DeviceIndex', 'InstanceId', 'NetworkInterfaceId',
	'DestinationCidrBlock', 'GatewayId', 'InstanceId', 'NetworkInterfaceId', 'RouteTableId', 'VpcPeeringConnectionId',
	'VpcId', 'Tags',
	'GroupDescription', 'SecurityGroupEgress', 'SecurityGroupIngress', 'Tags', 'VpcId',
	'CidrIp', 'DestinationSecurityGroupId', 'FromPort', 'GroupId', 'IpProtocol', 'ToPort',
	'CidrIp', 'FromPort', 'GroupId', 'GroupName', 'IpProtocol', 'SourceSecurityGroupId', 'SourceSecurityGroupName', 'SourceSecurityGroupOwnerId', 'ToPort',
	'AvailabilityZone', 'CidrBlock', 'MapPublicIpOnLaunch', 'Tags', 'VpcId',
	'SubnetId', 'NetworkAclId',
	'RouteTableId', 'SubnetId',
	'AvailabilityZone', 'Encrypted', 'Iops', 'KmsKeyId', 'Size', 'SnapshotId', 'Tags', 'VolumeType',
	'Device', 'InstanceId', 'VolumeId',
	'CidrBlock', 'EnableDnsSupport', 'EnableDnsHostnames', 'InstanceTenancy', 'Tags',
	'DhcpOptionsId', 'VpcId',
	'InternetGatewayId', 'VpcId', 'VpnGatewayId',
	'PeerVpcId', 'Tags', 'VpcId',
	'Type', 'CustomerGatewayId', 'StaticRoutesOnly', 'Tags', 'VpnGatewayId',
	'DestinationCidrBlock', 'VpnConnectionId',
	'Type', 'Tags',
	'RouteTableIds', 'VpnGatewayId',
	'Cluster', 'DesiredCount', 'LoadBalancers', 'Role', 'TaskDefinition',
	'ContainerDefinitions', 'Volumes',
	'AutoMinorVersionUpgrade', 'AZMode', 'CacheNodeType', 'CacheParameterGroupName', 'CacheSecurityGroupNames', 'CacheSubnetGroupName', 'ClusterName', 'Engine', 'EngineVersion', 'NotificationTopicArn', 'NumCacheNodes', 'Port', 'PreferredAvailabilityZone', 'PreferredAvailabilityZones', 'PreferredMaintenanceWindow', 'SnapshotArns', 'SnapshotName', 'SnapshotRetentionLimit', 'SnapshotWindow', 'VpcSecurityGroupIds',
	'CacheParameterGroupFamily', 'Description', 'Properties',
	'AutomaticFailoverEnabled', 'AutoMinorVersionUpgrade', 'CacheNodeType', 'CacheParameterGroupName', 'CacheSecurityGroupNames', 'CacheSubnetGroupName', 'Engine', 'EngineVersion', 'NotificationTopicArn', 'NumCacheClusters', 'Port', 'PreferredCacheClusterAZs', 'PreferredMaintenanceWindow', 'ReplicationGroupDescription', 'SecurityGroupIds', 'SnapshotArns', 'SnapshotRetentionLimit', 'SnapshotWindow',
	'Description',
	'CacheSecurityGroupName', 'EC2SecurityGroupName', 'EC2SecurityGroupOwnerId',
	'Description', 'SubnetIds',
	'ApplicationName', 'Description',
	'ApplicationName', 'Description', 'SourceBundle',
	'ApplicationName', 'Description', 'EnvironmentId', 'OptionSettings', 'SolutionStackName', 'SourceConfiguration',
	'ApplicationName', 'CNAMEPrefix', 'Description', 'EnvironmentName', 'OptionSettings', 'SolutionStackName', 'TemplateName', 'Tier', 'VersionLabel',
	'AccessLoggingPolicy', 'AppCookieStickinessPolicy', 'AvailabilityZones', 'ConnectionDrainingPolicy', 'ConnectionSettings', 'CrossZone', 'HealthCheck', 'Instances', 'LBCookieStickinessPolicy', 'LoadBalancerName', 'Listeners', 'Policies', 'Scheme', 'SecurityGroups', 'Subnets', 'Tags',
	'Serial', 'Status', 'UserName',
	'ManagedPolicyArns', 'Path', 'Policies',
	'Path', 'Roles',
	'Description', 'Groups', 'Path', 'PolicyDocument', 'Roles', 'Users',
	'Groups', 'PolicyDocument', 'PolicyName', 'Roles', 'Users',
	'AssumeRolePolicyDocument', 'ManagedPolicyArns', 'Path', 'Policies',
	'Groups', 'LoginProfile', 'ManagedPolicyArns', 'Path', 'Policies',
	'GroupName', 'Users',
	'ShardCount',
	'Code', 'Description', 'Handler', 'MemorySize', 'Role', 'Runtime', 'Timeout', 
	'RetentionInDays',
	'FilterPattern', 'LogGroupName', 'MetricTransformations',
	'AppSource', 'Attributes', 'Description', 'Domains', 'EnableSsl', 'Name', 'Shortname', 'SslConfiguration', 'StackId', 'Type',
	'ElasticLoadBalancerName', 'LayerId',
	'AmiId', 'Architecture', 'AutoScalingType', 'AvailabilityZone', 'InstallUpdatesOnBoot', 'InstanceType', 'LayerIds', 'Os', 'RootDeviceType', 'SshKeyName', 'StackId', 'SubnetId', 'TimeBasedAutoScaling',
	'Attributes', 'AutoAssignElasticIps', 'AutoAssignPublicIps', 'CustomInstanceProfileArn', 'CustomRecipes', 'CustomSecurityGroupIds', 'EnableAutoHealing', 'InstallUpdatesOnBoot', 'LifecycleEventConfiguration', 'LoadBasedAutoScaling', 'Name', 'Packages', 'Shortname', 'StackId', 'Type', 'VolumeConfigurations',
	'Attributes', 'ChefConfiguration', 'ConfigurationManager', 'CustomCookbooksSource', 'CustomJson', 'DefaultAvailabilityZone', 'DefaultInstanceProfileArn', 'DefaultOs', 'DefaultRootDeviceType', 'DefaultSshKeyName', 'DefaultSubnetId', 'HostnameTheme', 'Name', 'ServiceRoleArn', 'UseCustomCookbooks', 'UseOpsworksSecurityGroups', 'VpcId',
	'AllowVersionUpgrade', 'AutomatedSnapshotRetentionPeriod', 'AvailabilityZone', 'ClusterParameterGroupName', 'ClusterSecurityGroups', 'ClusterSubnetGroupName', 'ClusterType', 'ClusterVersion', 'DBName', 'ElasticIp', 'Encrypted', 'HsmClientCertificateIdentifier', 'HsmConfigurationIdentifier', 'MasterUsername', 'MasterUserPassword', 'NodeType', 'NumberOfNodes', 'OwnerAccount', 'Port', 'PreferredMaintenanceWindow', 'PubliclyAccessible', 'SnapshotClusterIdentifier', 'SnapshotIdentifier', 'VpcSecurityGroupIds', 
	'Description', 'ParameterGroupFamily', 'Parameters', 
	'Description', 
	'ClusterSecurityGroupName', 'CIDRIP', 'EC2SecurityGroupName', 'EC2SecurityGroupOwnerId',
	'Description', 'SubnetIds', 
	'AllocatedStorage', 'AllowMajorVersionUpgrade', 'AutoMinorVersionUpgrade', 'AvailabilityZone', 'BackupRetentionPeriod', 'CharacterSetName', 'DBInstanceClass', 'DBInstanceIdentifier', 'DBName', 'DBParameterGroupName', 'DBSecurityGroups', 'DBSnapshotIdentifier', 'DBSubnetGroupName', 'Engine', 'EngineVersion', 'Iops', 'KmsKeyId', 'LicenseModel', 'MasterUsername', 'MasterUserPassword', 'MultiAZ', 'OptionGroupName', 'Port', 'PreferredBackupWindow', 'PreferredMaintenanceWindow', 'PubliclyAccessible', 'SourceDBInstanceIdentifier', 'StorageEncrypted', 'StorageType', 'Tags', 'VPCSecurityGroups',
	'Description', 'Family', 'Parameters', 'Tags',
	'DBSubnetGroupDescription', 'SubnetIds', 'Tags',
	'EC2VpcId', 'DBSecurityGroupIngress', 'GroupDescription', 'Tags',
	'CIDRIP', 'DBSecurityGroupName', 'EC2SecurityGroupId', 'EC2SecurityGroupName', 'EC2SecurityGroupOwnerId',
	'Enabled', 'EventCategories', 'SnsTopicArn', 'SourceIds', 'SourceType',
	'EngineName', 'MajorEngineVersion', 'OptionGroupDescription', 'OptionConfigurations', 'Tags',
	'HealthCheckConfig', 'HealthCheckTags',
	'HostedZoneConfig', 'HostedZoneTags', 'Name', 'VPCs',
	'AliasTarget', 'Comment', 'Failover', 'GeoLocation', 'HealthCheckId', 'HostedZoneId', 'HostedZoneName', 'Name', 'Region', 'ResourceRecords', 'SetIdentifier', 'TTL', 'Type', 'Weight',
	'HostedZoneId', 'HostedZoneName', 'RecordSets', 'Comment',
	'AccessControl', 'BucketName', 'CorsConfiguration', 'LifecycleConfiguration', 'LoggingConfiguration', 'NotificationConfiguration', 'Tags', 'VersioningConfiguration', 'WebsiteConfiguration',
	'Bucket', 'PolicyDocument',
	'DisplayName', 'Subscription', 'TopicName',
	'PolicyDocument', 'Topics',
	'DelaySeconds', 'MaximumMessageSize', 'MessageRetentionPeriod', 'QueueName', 'ReceiveMessageWaitTimeSeconds', 'RedrivePolicy', 'VisibilityTimeout',
	'PolicyDocument', 'Queues',
	//CFN Helpers
	'config', 'packages', 'groups', 'users', 'sources', 'files', 'commands', 'services', 'configSets',
	'command', 'env', 'cwd', 'test', 'ignoreErrors', 'waitAfterCompletion',
	'content', 'source', 'encoding', 'group', 'owner', 'mode', 'authentication', 'context',
	'gid',
	'ensureRunning', 'enabled', 'files', 'sources', 'packages', 'commands',
	'uid', 'groups', 'homeDir',
	//Resource property types
	'DeviceName', 'Ebs', 'NoDevice', 'VirtualName',
	'DeleteOnTermination', 'Iops', 'SnapshotId', 'VolumeSize', 'VolumeType',
	'Granularity', 'Metrics',
	'NotificationTypes', 'TopicARN',
	'Key', 'Value', 'PropagateAtLaunch',
	'Parameters',
	'Aliases', 'CacheBehaviors', 'Comment', 'CustomErrorResponses', 'DefaultCacheBehavior', 'DefaultRootObject', 'Enabled', 'Logging', 'Origins', 'PriceClass', 'Restrictions', 'ViewerCertificate',
	'AllowedMethods', 'CachedMethods', 'ForwardedValues', 'MinTTL', 'PathPattern', 'SmoothStreaming', 'TargetOriginId', 'TrustedSigners', 'ViewerProtocolPolicy',
	'ErrorCachingMinTTL', 'ErrorCode', 'ResponseCode', 'ResponsePagePath',
	'AllowedMethods', 'CachedMethods', 'ForwardedValues', 'MinTTL', 'SmoothStreaming', 'TargetOriginId', 'TrustedSigners', 'ViewerProtocolPolicy',
	'Bucket', 'IncludeCookies', 'Prefix',
	'CustomOriginConfig', 'DomainName', 'Id', 'OriginPath', 'S3OriginConfig',
	'HTTPPort', 'HTTPSPort', 'OriginProtocolPolicy',
	'OriginAccessIdentity',
	'GeoRestriction',
	'Locations', 'RestrictionType',
	'CloudFrontDefaultCertificate', 'IamCertificateId', 'MinimumProtocolVersion', 'SslSupportMethod',
	'Cookies', 'Headers', 'QueryString',
	'Forward', 'WhitelistedNames',
	'Name', 'Value',
	'MetricName', 'MetricNamespace', 'MetricValue',
	'Attributes', 'Id',
	'Key', 'StringValue',
	'Id', 'StringValue',
	'Fields', 'Id', 'Name',
	'Key', 'RefValue', 'StringValue',
	'Key', 'Value',
	'AttributeName', 'AttributeType',
	'IndexName', 'KeySchema', 'Projection', 'ProvisionedThroughput',
	'AttributeName', 'KeyType',
	'IndexName', 'KeySchema', 'Projection',
	'NonKeyAttributes', 'ProjectionType',
	'ReadCapacityUnits', 'WriteCapacityUnits', 
	'DeviceName', 'Ebs', 'NoDevice', 'VirtualName',
	'DeleteOnTermination', 'Encrypted', 'Iops', 'SnapshotId', 'VolumeSize', 'VolumeType',
	'Code', 'Type',
	'Device', 'VolumeId',
	'AssociatePublicIpAddress', 'DeleteOnTermination', 'Description', 'DeviceIndex', 'GroupSet', 'NetworkInterfaceId', 'PrivateIpAddress', 'PrivateIpAddresses', 'SecondaryPrivateIpAddressCount', 'SubnetId',
	'AttachmentID', 'InstanceID', 'PublicIp', 'IpOwnerId', 
	'AttachmentID', 'InstanceID',
	'Key', 'Value',
	'PrivateIpAddress', 'Primary', 
	'From', 'To',
	'CidrIp', 'DestinationSecurityGroupId', 'FromPort', 'IpProtocol', 'SourceSecurityGroupId', 'SourceSecurityGroupName', 'SourceSecurityGroupOwnerId', 'ToPort', 
	'ContainerName', 'ContainerPort', 'LoadBalancerName',
	'Command', 'Cpu', 'EntryPoint', 'Environment', 'Essential', 'Image', 'Links', 'Memory', 'MountPoints', 'Name', 'PortMappings', 'VolumesFrom',
	'Name', 'Value',
	'ContainerPath', 'SourceVolume', 'ReadOnly',
	'ContainerPort', 'HostPort',
	'SourceContainer', 'ReadOnly',
	'Name', 'Host',
	'SourcePath',
	'Name', 'Type', 'Version',
	'Namespace', 'OptionName', 'Value',
	'S3Bucket', 'S3Key',
	'ApplicationName', 'TemplateName',
	'EmitInterval', 'Enabled', 'S3BucketName', 'S3BucketPrefix',
	'CookieName', 'PolicyName',
	'Enabled', 'Timeout',
	'IdleTimeout',
	'HealthyThreshold', 'Interval', 'Target', 'Timeout', 'UnhealthyThreshold',
	'CookieExpirationPeriod', 'PolicyName',
	'InstancePort', 'InstanceProtocol', 'LoadBalancerPort', 'PolicyNames', 'Protocol', 'SSLCertificateId',
	'Attributes', 'InstancePorts', 'LoadBalancerPorts', 'PolicyName', 'PolicyType',
	'PolicyDocument', 'PolicyName',
	'Password', 'PasswordResetRequired',
	'S3Bucket', 'S3Key', 'S3ObjectVersion',
	'CpuThreshold', 'IgnoreMetricsTime', 'InstanceCount', 'LoadThreshold', 'MemoryThreshold', 'ThresholdsWaitTime',
	'BerkshelfVersion', 'ManageBerkshelf',
	'ShutdownEventConfiguration',
	'DelayUntilElbConnectionsDrained', 'ExecutionTimeout',
	'DownScaling', 'Enable', 'UpScaling',
	'Configure', 'Deploy', 'Setup', 'Shutdown', 'Undeploy',
	'Password', 'Revision', 'SshKey', 'Type', 'Url', 'Username',
	'Certificate', 'Chain', 'PrivateKey',
	'Name', 'Version',
	'Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday',
	'Iops', 'MountPoint', 'NumberOfDisks', 'RaidLevel', 'Size', 'VolumeType',
	'ParameterName', 'ParameterValue',
	'Key', 'Value',
	'DBSecurityGroupMemberships', 'OptionName', 'OptionSettings', 'Port', 'VpcSecurityGroupMemberships', 
	'Name', 'Value',
	'CIDRIP', 'EC2SecurityGroupId', 'EC2SecurityGroupName', 'EC2SecurityGroupOwnerId', 
	'DNSName', 'EvaluateTargetHealth', 'HostedZoneId',
	'ContinentCode', 'CountryCode', 'SubdivisionCode',
	'FailureThreshold', 'FullyQualifiedDomainName', 'IPAddress', 'Port', 'RequestInterval', 'ResourcePath', 'SearchString', 'Type',
	'Key', 'Value',
	'Comment',
	'Key', 'Value',
	'VPCId', 'VPCRegion',
	'CorsRules',
	'AllowedHeaders', 'AllowedMethods', 'AllowedOrigins', 'ExposedHeaders', 'Id', 'MaxAge',
	'Rules',
	'ExpirationDate', 'ExpirationInDays', 'Id', 'NoncurrentVersionExpirationInDays', 'NoncurrentVersionTransition', 'Prefix', 'Status', 'Transition',
	'StorageClass', 'TransitionInDays',
	'StorageClass', 'TransitionDate', 'TransitionInDays',
	'DestinationBucketName', 'LogFilePrefix',
	'TopicConfigurations',
	'Event', 'Topic',
	'Status',
	'ErrorDocument', 'IndexDocument', 'RedirectAllRequestsTo', 'RoutingRules',
	'HostName', 'Protocol',
	'RedirectRule', 'RoutingRuleCondition',
	'HostName', 'HttpRedirectCode', 'Protocol', 'ReplaceKeyPrefixWith', 'ReplaceKeyWith',
	'HttpErrorCodeReturnedEquals', 'KeyPrefixEquals',
	'Endpoint', 'Protocol', 
	'deadLetterTargetArn', 'maxReceiveCount',
	//Resource attributes
	'CreationPolicy', 'ResourceSignal', 'Count', 'Timeout',
	'DeletionPolicy', 'Delete', 'Retain', 'Snapshot',
	'DependsOn',
	'Metadata',
	'UpdatePolicy', 'AutoScalingRollingUpdate', 'MaxBatchSize', 'MinInstancesInService', 'PauseTime', 'SuspendProcesses', 'WaitOnResourceSignals', 'AutoScalingScheduledAction', 'IgnoreUnmodifiedGroupSizeProperties'
);

console.log(names.sort().toString().replace(/,/gi,'|'));